### ISSUE TITLE
How to use your work?

### ISSUE THREAD

**Issue by goofy2k** [victorzheleznov/phase-modulation-synthesizer#5]
I forked your repo and am eager to use it in JUCE / Visual Studio 2022, but I have some problems with following your instructions:

Step 1. Done  
Step 2. I don't see the check boxes that you mention. I use Projucer V8.0.4.  (I now just checked all boxes ;-) )
Step 3. How to add the source code before going to step 4 ?
Step 4. After Pressing "Create Project"  Visual Studio 2022 opens and I see this:

![Screenshot 2024-12-14 211915](https://github.com/user-attachments/assets/d971c8eb-06e5-4be6-9bf3-671c57ef7469)

I hope that you can help me!

**Comment by goofy2k** [comment]
OK I found the settings under step 2 in the Projucer environment.   I copied your source codes into the Visual Studio 2022 project folder after creating the project.

The code compiles well. When running I see a window where I can enter all kinds of settings. But I have no way to listen to the sound. There is no button to play the sound or a keyboard.....

**Comment by goofy2k** [comment]
Success! I installed "virtualKeys" and "loopMidi" by Tobias Erichsen. Now I can play with your synth !

**Comment by victorzheleznov** [comment]
Hi! Sorry I couldn't respond earlier to help you with instructions. Looks like you've figured everything out :) To test/play with the synth you could also use the JUCE Plugin Host (see "Set up plug-in debugging" section [here](https://docs.juce.com/master/tutorial_create_projucer_basic_plugin.html)) or use the compiled VST3 plug-in in any DAW (like Reaper which has a generous free trial).

**Comment by goofy2k** [comment]
Thanks for replying! It looks like I just had (have!) to discover the
ecosystem!

Op zo 15 dec 2024 om 15:01 schreef Victor Zheleznov <
***@***.***>:
